version: '3'
services:
  grid:
    build: .
    command: python main.py
    volumes:
      - ".:/workdir"
    env_file:
      .env

  web:
    build: .
    command: python -m flask run --no-debugger
    ports:
      - "80:5000"
    volumes:
      - ".:/workdir"
    